### PR TITLE
Out-of-band data + SSH Agent forwarding

### PR DESCRIPTION
**Pull request by rinne**
Pluggable out of band communication mechanism over Mosh transport
layer and agent forwarding support in top of out of band mechanism.

I contrubute this code to Mosh project under the same license that
Mosh itself is distributed. All licensing options and clauses
included.

Signed-off-by: Timo J. Rinne <tri@iki.fi>

### CODE REVIEW

**Comment by GothAck** [comment]
Any movement on this patch? I see there are now merge conflicts. Mosh supporting OOB data, including ssh-agent, would be an amazingly useful thing to have.

**Comment by GothAck** [comment]
@rinne Getting build warning from the merged branch in your repo, was this introduced with your merge of the conflicts? The debuild script treats warnings as errors.
```
outofband.h:60:9: error: ‘class Network::OutOfBandCommunicator’ has pointer data members [-Werror=effc++]
   class OutOfBandCommunicator
         ^
outofband.h:60:9: error:   but does not override ‘Network::OutOfBandCommunicator(const Network::OutOfBandCommunicator&)’ [-Werror=effc++]
outofband.h:60:9: error:   or ‘operator=(const Network::OutOfBandCommunicator&)’ [-Werror=effc++]
cc1plus: all warnings being treated as errors
```
Could you perhaps add a merge commit to this branch and push? IIRC that should be added to the PR.

**Comment by rinne** [comment]
My compilation in OpenSuse or in OSX (under macports) doesn't get that warning and I don't have time to decipher that. Maybe you can fix it and send me a patch against ssh-agent-forwarding branch?

**Comment by Kriechi** [comment]
@rinne any chance you could rebase and fix the conflicts?
@keithw any final verdict on this PR?

would be a really cool feature to have merged!

**Comment by JonLundy** [comment]
+1

**Comment by rinne** [comment]
I probably won't do anything to it, if there is no clear indication that it's going to be merged. Meanwhile the agent enabled version can be compiled from my repo.

repo: https://github.com/rinne/mosh.git
branch: ssh-agent-forwarding

**Comment by ryanpetrello** [comment]
:+1:

**Pull request closed without merging**
