### PR TITLE
OS X build improvements (WIP)

### PR DESCRIPTION
**Pull request by cgull**
This isn't finished or fully working yet but is worth showing around.

This is basically a complete rewrite of macosx/build.sh to better detect local setup, support pkgbuild/productbuild as well as PackageMaker, and to build whatever architectures the installed SDK supports.  The build seems to work well on OS X 10.9 + XCode 6.3 + Homebrew.  The build is (just now) successful on OS X 10.5 + XCode 3.1 + MacPorts (not updated since, oh, 2009), but mosh-client bus-errors on startup.

The 10.5 machine I'm testing this with has protobufs 2.0.2, which is ancient.  I had to make some source changes to support that, which I'm dubious about.  As I'm writing this, I'm realizing I should go through the pain of upgrading Macports or replacing it with Tigerbrew to get a slightly more reasonable build environment.

One more thing I did is change the install location.  The old package installed into /usr/bin + /usr/share/man, which is a rather bad idea on OS X, and it appears that Rootless mode in OS X 10.11 will break that.  So it now installs into /usr/local (which might still be broken for Rootless, I don't know).

@eminence, I'd appreciate it if you could try this build on your Mac and report what you get...

### CODE REVIEW

**Comment by eminence** [comment]
Looks good on my machine.  At least, the .pkg file was built sucessfully.  I'm not physically at the machine at the moment, but once I am I'll try running the installer and will report back here

**Comment by cgull** [comment]
Thanks, that's what I wanted to know.  Did you notice whether it built with pkgbuild or PackageMaker?

**Comment by eminence** [comment]
It was built with `pkgbuild`

**Comment by chickenandpork** [comment]
@eminence are you releasing these to App Store?  If not I'm willing as a blind build-and-ship.  I can also set up a XServer continuous integration bot

**Comment by cgull** [comment]
OK, I think this is my final spin.
@eminence, can you build + install this on your machine?  (And on any other Mac you might have around-- I ran into a portability problem with Homebrew libraries.  Read the top of macosx/build.sh for details)
@chickenandpork, I think an App Store release with your developer signature would be up to @keithw, and the build would likely need more work to satisfy Apple guidelines and app testing.  I think everybody would love an OS X CI bot, though.

**Comment by eminence** [comment]
(Already mentioned this to cgull in IRC, but for the record, i'll repeat it here)

This builds and installs fine on my machine.  OSX 10.9.5, Xcode 5.1.1 and Macports 2.3.2.   

All previous OSX builds have just been hosted on the mosh homepage (could also be hosted on github as well).  I'm not in a position to do anything related to the App Store, so i defer to others on how that could/should be handled.

**Comment by cgull** [comment]
There is one unfortunate issue with the revised build:  Moving mosh-server to /usr/local/bin means that it is no longer on the OS X default path, and people mosh-ing *into* Macintoshes will need to specify `--server=/usr/local/bin/mosh-server`.

**Comment by chickenandpork** [comment]
Hi @cgull;

I couldn't find a preferred contact means for Keith.  Does he watch this
space, or is it merely an mit.edu address of his username?  (which I hope
is enough to explain yet avoid email-harvesting bots)

Allan

On Sun, Jun 21, 2015 at 9:49 AM, cgull <notifications@github.com> wrote:

> OK, I think this is my final spin.
> @eminence <https://github.com/eminence>, can you build + install this on
> your machine? (And on any other Mac you might have around-- I ran into a
> portability problem with Homebrew libraries. Read the top of
> macosx/build.sh for details)
> @chickenandpork <https://github.com/chickenandpork>, I think an App Store
> release with your developer signature would be up to @keithw
> <https://github.com/keithw>, and the build would likely need more work to
> satisfy Apple guidelines and app testing. I think everybody would love an
> OS X CI bot, though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keithw/mosh/pull/633#issuecomment-113927074>.
>



-- 
allanc@chickenandporn.com  "金鱼" http://linkedin.com/in/goldfish

**Comment by cgull** [comment]
He's at Stanford University now:  <http://cs.stanford.edu/~keithw/>

**Comment by keithw** [comment]
Also on GitHub if it's Mosh-related...

**Comment by cgull** [comment]
@keithw, @eminence, others-- are you happy with the choice of `/usr/local` for the package?  I believe this is the Right Thing to Do, but I want to get to consensus here.

**Comment by keithw** [comment]
I'm going to defer to the Mac people on this one. I don't have a view myself. If we can get Mac people to test the package and they're satisfied, that's fine by me. (How will it interact with previous versions of the Mosh binary package?)

**Comment by cgull** [comment]
The OS X package system is broken in oh so many ways, but it **does** seem to handle these upgrades OK-- it deletes the old files on their old paths.

**Comment by eminence** [comment]
i found a few old .pkg files from previous mosh releases, and these actually install into `/usr/bin`  I didn't attempt to figure out why, yet.

**Pull request closed without merging**
