### PR TITLE
scripts/mosh: Fix hang when remote closes the connection

### PR DESCRIPTION
**Pull request by andersk**
Signed-off-by: Anders Kaseorg <andersk@mit.edu>

### CODE REVIEW

**Comment by andersk** [comment]
@cgull: As a consequence of the confusing way in which GitHub pull requests work, you should leave comments on the central [pull request page](https://github.com/keithw/mosh/pull/490), not on the author’s commit page. (Line comments go on the [“Files changed” tab](https://github.com/keithw/mosh/pull/490/files).) That way the comments are not lost when the pull request is force-pushed, and comment notifications go to everyone interested in the pull request instead of just the opener.

**Comment by cgull** [comment]
Thanks for the tip.
Never mind my comment; I tried it and it doesn't work, and your code does.  Neither of them work at the command line.
I think the fake-proxy data-passing code could stand a rewrite-- but this is a fine band-aid.

**Comment by cgull** [comment]
Pulled.

**Comment by cgull** [comment]
Oops, wrong issue.  Not this one.  Nothing pulled here.  Move along, this isn't the issue you're looking for.

**Pull request closed without merging**
